---
title: "DURIN 2026 Thermal Tolerance Calluna T50 Response Curves"
author: "Sonya R Geange and Gaëlle Poulat"
format: html
editor: visual
---

```{r}
#| label: setup
#| message: false 

# installing / loading packages
library(readxl) # Enables excel file import
library(tidyverse) # Contains many helpful packages, i.e. dplyr etc.
library(janitor) # Has tools for data cleaning 
library(lubridate) # Date and time formatting
library(readr) # Data importation functions
library(stringr) # String and character text
library(future) # Using severals cores at the same time
library(ggcorrplot)
library(emmeans)
library(car) # for the Anova
library(dplyr)
# install.packages("remotes")
# remotes::install_github("richardjtelford/thermalTolerance")
library(thermalTolerance)

library(future)
```

# Import data

```{r}
#| label: importing-clean-data

data <- read.csv2("C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/clean_data/Seasonal Calluna Thermal Tolerance and Plant Functional Traits.csv")
```

# Hot T50 curves

```{r}
#| label: Create-hot-data-frame
# Create table with four columns
therm_htol <- data |>
  filter(!(month == "March" &
             age_class %in% c("Mature", "Building"))) |>  # We did not keep MAT and BUI in March because they were mainly initially dead (based on the Fv/Fm graph). Consequently, we could not obtain a T50 curve or a T50 estimation for those age classes.
  filter(proj_2025 == "TT Hot") |>
  select(
    month,
    site_name,
    species,
    age_class,
    leaf_age,
    proj_2025,
    plant_nr,
    temp_exp,
    fv_fm_final
  )
```

```{r}
#| label: concatenated-columns-per-plant


# Create concatenated columns for naming
united_columns_htol_plant <- unite(
  therm_htol,
  col = "new_id",
  site_name,
  species,
  age_class,
  plant_nr,
  month,
  leaf_age,
  proj_2025,
  sep = "_",
  remove = TRUE
) |>
  na.omit()

# NA for BUI 4 14 May young 
# NA for PIO 1 7 Nov
# NA for BUI 3 May old, BUI 2 May young, MAT 7 May young --> no leaf harvested
```

## Curves

```{r}
#| label: T50-curves-and-plots-per-plant
#| warning: false

#first run for every plantes exepte bui and mat of march because already dead before the experiment


plan(multisession) # activate parallel processing
set.seed(19) # avoir la même chose a chaque fois comme ça il n'y a pas des moments où ça marche et d'autres non
# united_columns_htol_plant2 <- united_columns_htol_plant |> filter(between(group_indices(), 56, 100), .by = "new_id")

TTHot_plant <- psiiht(temperature = united_columns_htol_plant$temp_exp, 
               warming = TRUE,
               fvfm = united_columns_htol_plant$fv_fm_final,
               control_temp = 20,
               id = united_columns_htol_plant$new_id,
               boots = 1000)# put 1000

TTHot_plant_sum <- summary(TTHot_plant) # see summary output for T50 values (note, just means)

autoplot(TTHot_plant) # plots logistic curves and dashed lines for Tcrit, T50, T95


#saving

saveRDS(TTHot_plant, file = "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/TTHot_plant_results.rds")

write.csv2(
  TTHot_plant_sum, 
  file = "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/TTHot_plant_sum.csv", 
  row.names = FALSE
)
```

```{r}
#| label: T50-curves-unsucessful
#| warning: false

# second run for the one that could give us a courbe before but didn't because of the random choice and seed 19
#liste des plantes qui n'ont pas fait de courbes mais aurait pu

unsucessful_Hot_T50_curves <- united_columns_htol_plant |>
  filter(
    new_id %in% c(
      "Lygra_Calluna vulgaris_Building_3_July_young_TT Hot",
      "Lygra_Calluna vulgaris_Building_6_July_young_TT Hot",
      "Lygra_Calluna vulgaris_Building_6_May_young_TT Hot",
      "Lygra_Calluna vulgaris_Building_8_May_old_TT Hot",
      "Lygra_Calluna vulgaris_Mature_3_July_young_TT Hot",
      "Lygra_Calluna vulgaris_Mature_4_July_young_TT Hot",
      "Lygra_Calluna vulgaris_Newly Burnt_2_July_young_TT Hot",
      "Lygra_Calluna vulgaris_Newly Burnt_5_May_young_TT Hot"
    )
  )

unsucessful_Hot_T50_curves |>
  mutate(temp_exp = as.numeric(as.character(temp_exp)),
         fv_fm_final = as.numeric(as.character(fv_fm_final))) |>
  ggplot(aes(x = temp_exp, y = fv_fm_final, color = new_id)) +
  facet_grid(new_id ~ .) +
  geom_line()

# On remarque qu'il y a un pique à 46 pour ces courbes mes on distingues aussi clairement un pente qui pourrait nous donner une T50. Essayer de reborner la courbe.
```

```{r}
# #| label: T50-curves-unsucessful-new-run
# #| warning: false
# 
# # on reborne la courbes entre 46 et 56 car 46 est le point le plus élevée pour ces courbes et on refait les T50 reponse curves
# set.seed(19)
# 
# unsucessful_Hot_T50_curves_filtered <- unsucessful_Hot_T50_curves |>
#   filter(temp_exp >= 44 & temp_exp <= 56)
# 
# plan(multisession)
# 
# 
# # 4. Lancer psiiht directement sur ton nouveau tableau
# TTHot_run_2 <- psiiht(
#   temperature  = unsucessful_Hot_T50_curves_filtered$temp_exp, 
#   warming      = TRUE,
#   fvfm         = unsucessful_Hot_T50_curves_filtered$fv_fm_final,
#   control_temp = 44,
#   id           = unsucessful_Hot_T50_curves_filtered$new_id,
#   boots        = 1000
# )
# 
# # 5. Résumé et graphiques
# TTHot_run_2_sum <- summary(TTHot_run_2)
# 
# 
# autoplot(TTHot_run_2)
# 
# #seulement une courbe se trace, et son prop_sucess est de 0.2 ce qui n'est pas suffisant. --> tant pis.
```

## Barres d'erreurs

```{r}
#| label: T50-curves-and-plots-per-plant
#| warning: false


summarise_htol_plant <- function(res, id) {

  if (is.null(res)) {
    return(data.frame(
      id = id,
      metric = c("T50", "T95", "Tcrit"),
      estimate = NA,
      se = NA,
      lower = NA,
      upper = NA
    ))
  }
  
  data.frame(
    id = id,
    metric = c("T50", "T95", "Tcrit"),
    estimate = c(median(res$T50, na.rm = TRUE),
                 median(res$T95, na.rm = TRUE),
                 median(res$Tcrit, na.rm = TRUE)),
    se = c(sd(res$T50, na.rm = TRUE),
           sd(res$T95, na.rm = TRUE),
           sd(res$Tcrit, na.rm = TRUE)),
    lower = c(quantile(res$T50, 0.025, na.rm = TRUE),
              quantile(res$T95, 0.025, na.rm = TRUE),
              quantile(res$Tcrit, 0.025, na.rm = TRUE)),
    upper = c(quantile(res$T50, 0.975, na.rm = TRUE),
              quantile(res$T95, 0.975, na.rm = TRUE),
              quantile(res$Tcrit, 0.975, na.rm = TRUE))
  )
}

# Run the summarize function for each ID output

TTHot_plant <- readRDS("C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/TTHot_plant_results.rds")

TTHot_plant_out <- Map(
  summarise_htol_plant, # function
  TTHot_plant$results, # extract the results part of the psiiht output
  names(TTHot_plant$results)  # extract the ID from the psiiht output
  )
# Create the dataframe by rowbinding
TTHot_thermal_plant <- do.call(rbind, TTHot_plant_out)

TTHot_plant_sum <- read.csv2("C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/TTHot_plant_sum.csv")

TTHot_plant_success <- TTHot_plant_sum |>
  select(id, prop_success)

#fusion du tableau avec les prope sucess et du tableau avec les estimation leurs erreurs
TTHot_thermal_plant_combined <- TTHot_thermal_plant |>
  left_join(TTHot_plant_success, by = "id")

# String split back to columns the ID
TTHot_wide_plant <- TTHot_thermal_plant_combined |>
  separate_wider_delim(
    cols = id, # the column to split
    delim = "_", # how is the column seperated
    # what should the new columns be called - do in order
    names = c("site_name", "species", "age_class", "plant_nr", "month", "leaf_age", "proj_2025") #,
   # too_many = "merge", # Merges any extra parts into the last column
   # too_few = "align_start" # Fills missing values with NA
  ) |>
  # Check the data type of the new output columns and convert if necessary
   mutate(
    age_class = factor(age_class),
    proj_2025 = factor(proj_2025),
    site_name = factor(site_name),
    month = factor(month),
    leaf_age = factor(leaf_age),
    species = factor(species),
    plant_nr = factor(plant_nr)
  ) |>
  # Relevel factors in natural order
  mutate(
    age_class = factor(age_class, levels = c("Newly Burnt","Pioneer", "Building", "Mature"))) |> 
  filter(metric == "T50")
```

## Cleaning T50 estimate

```{r}
#| label: cleaning-T50-estimate
#| warning: false

## on enlève les lignes ou le prop success est inf a 0.5.

TTHot_wide_plant_clean <- TTHot_wide_plant |> 
  filter(
    !is.nan(prop_success) & prop_success >= 0.5,
         )

write.csv2(
  TTHot_wide_plant_clean, 
  file = "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/clean_data/TTHot_wide_plant_clean.csv", 
  row.names = FALSE
)

```

## Plot

```{r}
#| label: T50-plots-per-plant
#| warning: false


TTHot_wide_plant_clean_plot <- TTHot_wide_plant_clean |>
  mutate(
    plant_nr = as.factor(plant_nr), 
    month = factor(month, levels = c("March", "May", "July")),
    age_class = factor(age_class, levels = c("Newly Burnt", "Pioneer", "Building","Mature"))
  )


p <- ggplot(TTHot_wide_plant_clean_plot, 
       aes(x = age_class,
           y = estimate,
           color = plant_nr)) +
  geom_point(size = 2,
             position = position_dodge(width = 0.6)) +
  geom_errorbar(aes(ymin = estimate - se, ymax = estimate + se),
                width = 0.2,
                position = position_dodge(width = 0.6)) +
  
  scale_color_manual(values = c(
    "1" = "#E69F00",
    "2" = "#56B4E9",
    "3" = "#009E73",
    "4" = "#F0E442", 
    "5" = "#0072B2", 
    "6" = "#D55E00", 
    "7" = "#CC79A7",
    "8" = "#999999",
    "10" = "#1170AA",
    "18" = "#A6761D"
    )) +
  
  facet_grid(month ~ leaf_age, drop = FALSE) + 
  labs(
    x = "Age class",
    y = "T50 (°C)",
    color = "Plant number",
    title = bquote("Hot tolerance ("*T[50]*") of" ~ italic("Calluna vulgaris") ~ "across different age classes and seasons"),
    subtitle = "Points represent bootstrap means; bars show ±1 SE"
  ) +
  stat_summary(
    aes(group = age_class),
    fun.data = function(y) {
      data.frame(y = 30, label = paste0("n = ", length(y))) 
    },
    geom = "text",
    color = "grey40",
    size = 3.2,
    vjust = 0
  ) +
  theme_bw()

print(p)

ggsave(
  filename = "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Figures/hot_tolerance_t50.png",
  plot = p,                             
  width = 10,                           
  height = 7,                           
  units = "in",                         
  dpi = 300                             
)

```

# Cold T50 curves

```{r}
#| label: Create-cold-data-frame
# Create table with four columns
therm_ctol <- data |>
  # filter(!(month == "March" &
  #            age_class %in% c("Mature", "Building"))) |>  # We did not keep MAT and BUI in March because they were mainly initially dead (based on the Fv/Fm graph). Consequently, we could not obtain a T50 curve or a T50 estimation for those age classes.
  filter(proj_2025 == "TT Cold") |>
  select(
    month,
    site_name,
    species,
    age_class,
    leaf_age,
    proj_2025,
    plant_nr,
    temp_exp,
    fv_fm_final
  )
```

```{r}
#| label: concatenated-columns-per-plant

united_columns_cold_plant <- unite(
  therm_ctol,
  col = "new_id",
  site_name,
  species,
  age_class,
  plant_nr,
  month,
  leaf_age,
  proj_2025,
  sep = "_",
  remove = TRUE
) |>
  na.omit()

# Convert the temperature values into numeric format to prevent formatting errors
united_columns_cold_plant$temp_num <- as.numeric(as.character(united_columns_cold_plant$temp_exp))

# Invert the temperature scale (-5, 0, 5, 10, 15, 20) to create a descending curve, ensuring the psiiht function can properly fit the model
united_columns_cold_plant$temp_exp_order <- united_columns_cold_plant$temp_num * -1
```

## Curves

```{r}
#| label: T50-cold-curves-per-plant
#| warning: false

# install.packages("remotes")
# remotes::install_github("richardjtelford/thermalTolerance")
library(thermalTolerance)

library(future)
plan(sequential)
plan(multisession) # activate parallel processing
set.seed(19) # avoir la même chose a chaque fois comme ça il n'y a pas des moments où ça marche et d'autres non  


TTCold_plant <- psiiht(temperature = united_columns_cold_plant$temp_exp_order, 
               warming = FALSE, # cold treatment
               fvfm = united_columns_cold_plant$fv_fm_final,
               control_temp = 0,
               id = united_columns_cold_plant$new_id,
               boots = 1000)# put 1000

TTCold_plant_sum <- summary(TTCold_plant) # see summary output for T50 values (note, just means)

autoplot(TTCold_plant) # plots logistic curves and dashed lines for Tcrit, T50, T95
# /!\ the plots are the other way around regarding the temperatures.

#saving

saveRDS(TTCold_plant, file = "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/TTCold_plant_results.rds")

write.csv2(
  TTCold_plant_sum, 
  file = "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/TTCold_plant_sum.csv", 
  row.names = FALSE
)

```

## Barres d'erreurs

```{r}
#| label: Cold-T50-plots-per-plant
#| warning: false

summarise_ctol_plant <- function(res, id) {
  
  if (is.null(res)) {
    return(data.frame(
      id = id,
      metric = c("T50", "T95", "Tcrit"),
      estimate = NA,
      se = NA,
      lower = NA,
      upper = NA
    ))
  } 

  data.frame(
    id = id,
    metric = c("T50", "T95", "Tcrit"),
    estimate = c(median(res$T50, na.rm = TRUE),
                 median(res$T95, na.rm = TRUE),
                 median(res$Tcrit, na.rm = TRUE)),
    se = c(sd(res$T50, na.rm = TRUE),
           sd(res$T95, na.rm = TRUE),
           sd(res$Tcrit, na.rm = TRUE)),
    lower = c(quantile(res$T50, 0.025, na.rm = TRUE),
              quantile(res$T95, 0.025, na.rm = TRUE),
              quantile(res$Tcrit, 0.025, na.rm = TRUE)),
    upper = c(quantile(res$T50, 0.975, na.rm = TRUE),
              quantile(res$T95, 0.975, na.rm = TRUE),
              quantile(res$Tcrit, 0.975, na.rm = TRUE))
  )
}

TTCold_plant <- readRDS("C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/TTCold_plant_results.rds")

# Run the summarize function for each ID output
TTCold_plant_out <- Map(
  summarise_ctol_plant, # function
  TTCold_plant$results, # extract the results part of the psiiht output
  names(TTCold_plant$results)  # extract the ID from the psiiht output
  )

# Create the dataframe by rowbinding
TTCold_thermal_plant <- do.call(rbind, TTCold_plant_out)

# Convert back to real cold temperature (°C), we multiply by -1 to reverse the model's trick and get true negative values.
TTCold_thermal_plant <- TTCold_thermal_plant |>
  mutate(
    estimate = estimate * -1,
    lower    = lower * -1,
    upper    = upper * -1,
    se       = abs(se) # Standard error stays positive as it measures variance
  )

TTCold_plant_sum <- read.csv2("C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/TTCold_plant_sum.csv")

TTCold_plant_success <- TTCold_plant_sum |>
  select(id, prop_success)

#fusion du tableau avec les prope sucess et du tableau avec les estimation leurs erreurs
TTCold_thermal_plant_combined <- TTCold_thermal_plant |>
  left_join(TTCold_plant_success, by = "id")

# String split back to columns the ID
TTCold_wide_plant <- TTCold_thermal_plant_combined  |>
  separate_wider_delim(
    cols = id, # the column to split
    delim = "_", # how is the column seperated
    # what should the new columns be called - do in order
    names = c("site_name", "species", "age_class", "plant_nr", "month", "leaf_age", "proj_2025") #,
   # too_many = "merge", # Merges any extra parts into the last column
   # too_few = "align_start" # Fills missing values with NA
  ) |> 
  # Check the data type of the new output columns and convert if necessary
   mutate(
    age_class = factor(age_class),
    proj_2025 = factor(proj_2025),
    site_name = factor(site_name),
    month = factor(month),
    leaf_age = factor(leaf_age),
    species = factor(species),
    plant_nr = factor(plant_nr)
  ) |> 
  # Relevel factors in natural order
  mutate(
    age_class = factor(age_class, levels = c("Newly Burnt","Pioneer", "Building", "Mature"))) |> 
  filter(metric == "T50")
```

## Cleaning T50 estimate

```{r}
#| label: cleaning-T50-estimate
#| warning: false

## on enlève les lignes ou le prop success est inf a 0.5.

TTCold_wide_plant_clean <- TTCold_wide_plant |> 
  filter(
    !is.nan(prop_success) & prop_success >= 0.5,
         )

write.csv2(
  TTCold_wide_plant_clean, 
  file = "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/clean_data/TTCold_wide_plant_clean.csv", 
  row.names = FALSE
)
```

## Plot

```{r}
#| label: T50-plots-per-plant
#| warning: false

TTCold_wide_plant_clean <- read.csv2("C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/clean_data/TTCold_wide_plant_clean.csv")

# Create a preliminary plot focusing on T50 metric

TTCold_wide_plant_clean_plot <- TTCold_wide_plant_clean |>
  mutate(
    plant_nr = as.factor(plant_nr), 
    month = factor(month, levels = c("March", "May", "July")),
    age_class = factor(age_class, levels = c("Newly Burnt", "Pioneer", "Building","Mature"))
  )

p <- ggplot(TTCold_wide_plant_clean_plot, 
       aes(x = age_class,
           y = estimate,
           color = plant_nr)) +
  geom_point(size = 2,
             position = position_dodge(width = 0.6)) +
  geom_errorbar(aes(ymin = estimate - se, ymax = estimate + se),
                width = 0.2,
                position = position_dodge(width = 0.6)) +
  
  scale_color_manual(values = c(
    "1" = "#E69F00", 
    "2" = "#56B4E9", 
    "3" = "#009E73", 
    "4" = "#F0E442", 
    "5" = "#0072B2", 
    "6" = "#D55E00", 
    "7" = "#CC79A7", 
    "8" = "#999999",
    "10" = "#1170AA",
    "18" = "#A6761D"
  )) +
  
  facet_grid(month ~ leaf_age, drop = FALSE) + 
  labs(
    x = "Age class",
    y = "T50 (°C)",
    color = "Plant number",
    title = bquote("Cold tolerance ("*T[50]*") of" ~ italic("Calluna vulgaris") ~ "across different age classes and seasons"),
    subtitle = "Points represent bootstrap means; bars show ±1 SE"
  ) +
  stat_summary(
    aes(group = age_class),
    fun.data = function(y) {
      data.frame(y = -15, label = paste0("n = ", length(y)))
    },
    geom = "text",
    color = "grey40",
    size = 3.2,
    vjust = 0
  ) +
  theme_bw()

ggsave(
  filename = "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Figures/cold_tolerance_t50.png",
  plot = p,                             
  width = 10,                           
  height = 7,                           
  units = "in",                         
  dpi = 300                             
)
```

## 
