---
title: "DURIN 2026 Thermal Tolerance Calluna Seasonal"
author: "Sonya R Geange and Gaëlle Poulat"
format: html
editor: visual
---

## Import Data

```{r}
#| label: loading libraries
#| message: false 

# installing / loading packages

library(readxl) # Enables excel file import
library(tidyverse) # Contains many helpful packages, i.e. dplyr etc.
library(janitor) # Has tools for data cleaning 
library(lubridate) # Date and time formatting
library(readr) # Data importation functions
library(stringr) # String and character text
```

```{r}
#| label: importing raw data of trait and fluorescence
#| message: false 

# Eventually this will download from the DURIN OSF
# For now, download the excel from google sheets and save in your projects 'raw_data' folder.
# If using projects just need "./filenam.xlsx'
# If not in projects, need full path name

# Read in fluorescence and plant functional trait data (excluding leaf area)
raw_data <- read_excel(
  "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/Seasonal Calluna Thermal Tolerance and Plant Functional Traits.xlsx", 
  sheet = "cv_mar26", # Choose the sheet from excel
  na = c("", "NA")) # NAs are actually imported as NAs, not as characters 
```

```{r}
#| label: clean trait dataset to match DURIN formatting


# Change some column names to snake_case standard
# Change any column names to match DURIN standards - some outlined here (https://github.com/Durin-project/Durin_data)
# Some information will be specific to traits, fluorescence etc.
# using slice() to remove the first three row of example data (ALWAYS CHECK!)

raw_data <- raw_data %>% 
  # New name then old name of column, including snake case ('_' and lower letters)
  rename(site_name = siteID,
         age_class = ageClass,
         collection_time = CollTime,
         paired_with = PairedWith,
         temp_exp = TempExp,
         temp_exp_time = TempExpTime,
         temp_exp_time_unit = TempExpTimeUnit,
         fv_fm_initial = 'Fv/Fm_Initial',
         fv_fm_hr = 'Fv/Fm_Hr',
         fv_fm_final = 'Fv/Fm_Final',
         height_flower = 'height(s)_flower',
         height_vegetative = 'height(s)_top',
         treatment_date = TreatmentDate,
         treatment_time = TreatmentTime) %>%  
  slice(-(1:3)) # Remove first three rows (excluding headers)


# Check variable types (character, numeric etc)
glimpse(raw_data)

# Changing classes of all variables that should be in class factor
raw_data <- raw_data %>%  
  mutate(across(c(site_name, species, proj_2025, project, age_class, plant_nr, leaf_age, sample, paired_with, calluna_shoot_type, temp_exp, temp_exp_time, temp_exp_time_unit, fv_fm_hr, scanned), as.factor))


# Changing classes of variables that should be in class dbl/numeric
raw_data <- raw_data |>
    mutate(across(c(fv_fm_initial, fv_fm_final, wet_mass_g, leaf_thickness_1_mm, leaf_thickness_2_mm, leaf_thickness_3_mm, dry_mass_g, height_flower, height_vegetative), as.numeric))

# Changing classes of all variables that should be in class integers
raw_data <- raw_data |>
    mutate(across(c(bulk_nr_leaves, leaf_nr), as.integer))

# Recheck data types again
glimpse(raw_data) 


# Order relevant variables (useful for plotting and order based analyses)
# age_class sorted from youngest to oldest

raw_data$age_class <- factor((raw_data$age_class),
                         levels = c("Newly Burnt", "Pioneer", 
                                    "Building", "Mature"))
# Check if changed successfully
levels(raw_data$age_class)


# Converting day, month, year column into one column on the format yyyy_mm_dd
# Convert collection time into proeper time format
# removing the day and year columns, keep month for data cleaning checking for now

raw_data <- raw_data %>% 
  mutate(date  = ymd_hm(paste(year, month, day,
                 format(collection_time, format = "%H:%M"))), .after = 1)  %>% 
  select(-c(day, year, collection_time)) 


glimpse(raw_data) 

# To help with plotting, make month an ordered factor (more useful one more months)
raw_data <- raw_data %>%
  mutate(month = factor(month, levels = c("November", "January", "March")))

# Create a unique plant_ID given age_class, month, and plant_nr
raw_data <- raw_data %>%   # assuming you already created Month/date_day earlier
  mutate(
    unique_plantID = paste(age_class, month, plant_nr, sep = "_")
  )%>% 
  mutate(envelope_ID = case_when(
    grepl("ADDX1933", envelope_ID) ~ "ADX1933",
    grepl("AGS", envelope_ID) ~ "AGS4838",
    TRUE ~ envelope_ID  # keeps all the other remarks the way they were
    ))#wrong barcode written
#ok!
```

```{r}
#| label: import leaf area dataset tidy and match to trait dataset


# Change this to your local repository where the four excel output files are stored
leaf_area_dir <- "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/scans/calluna_march2026/output/" 

# Import leaves from the directory where the files are saved, only .csv files, return the file paths (not just file names)
leaf_area_raw <- list.files(leaf_area_dir, pattern = "\\.csv$", full.names = TRUE) %>%
  # Give each element the name of the source file (remove directory path)
  setNames(basename(.)) %>%
  # Read each .csv file into R, combine into a single dataframe
  # Add an ID column, indicating the source file
  purrr::map_df(~ readr::read_csv(.x, show_col_types = FALSE), .id = "source_file")

#leaf_area_raw has only 2 columnes and we have to separate them
leaf_area_raw <- leaf_area_raw %>%
  separate(
    col =  `number;ID;n;leaf_area`,          # The column to separate
    into = c("number", "ID", "n", "leaf_area"), # Names for the new columns
    sep = ";",            # The delimiter to use for splitting
  )%>%
  #remove the column number
  select(-c(number))

# Clean and summarize files to get leaf area per envelopeID
leaf_area_raw <- leaf_area_raw %>%
  dplyr::select(-dplyr::matches("^Unnamed")) %>%   # drop index col if present
  dplyr::mutate(
    # Create new column names, and/or update the datatype for a given column
    envelope_ID = str_trim(as.character(ID)),
    leaf_area_scanned_bulk_nr = as.numeric(n),
    leaf_area_sum = as.numeric(leaf_area)
  ) %>%
  # remove old column, comments is deleted as should be in the trait datasheet area check tab
  select(-c(ID, n,leaf_area))




# Choose correct value per envelope_ID based on the source file, i.e. edited or not
leaf_area_clean <- leaf_area_raw %>% 
  # Use the phrase 'edited_images' in the file name to prioritize
  mutate(priority = if_else(str_detect(source_file, "edited_images"), 1, 2)) %>%  
  arrange(envelope_ID, priority) %>%   # ordering so preferred rows come first
  distinct(envelope_ID, .keep_all = TRUE) %>%   # keeping first row per ID
  select(-priority) # removing helper column

#ok! we have 165 enveloppes

# Join the clean leaf area db to the main trait db by the envelope ID
data <- raw_data %>%
  dplyr::mutate(envelope_ID = stringr::str_trim(as.character(envelope_ID))) %>%
  # Left join, keep values from x, and only matching rows in y (leaf_area_clean)
  dplyr::left_join(leaf_area_clean, by = "envelope_ID")

```

# Data Cleaning Entire Dataframe

Above was cleaning of column names, formatting of variables etc. Now we need to identify any mistakes in the data entry, outliers etc.

```{r}
#| label: standardize comments and remarks

# Find unique comments in the dataset
unique(data$remark)

# Multiple comment strings in the column (EXAMPLE ONLY AT THE MOMENT!)
## first observation : some REMARKS are the same but with capital letters for example

library(dplyr)
library(stringr)

data <- data %>%
  mutate(remark = tolower(remark))%>% #evrything is in small letter to remove all capital letter mistakes
  mutate(remark = case_when(
    age_class == "Building" & plant_nr == "1" & leaf_nr == "20" ~ paste(remark, "mostly brown", sep = "; "),
    age_class == "Building" & plant_nr == "6" & leaf_nr == "18" ~ paste(remark, "brown leaves", sep = "; "),
    age_class == "Newly Burnt" & plant_nr == "7" & leaf_nr == "16" & leaf_nr == "17" & leaf_nr == "18" & leaf_nr == "19" & leaf_nr == "20" ~ "partly brown leaves",
    age_class == "Building" & plant_nr == "8" & leaf_nr == "16" & leaf_nr == "17" & leaf_nr == "18" & leaf_nr == "19" & leaf_nr == "20" ~ paste(remark, "brown leaves", sep = "; "),
    grepl("liquid", remark) ~ "liquid water in bag",
    grepl("fridge", remark) ~ "not removed from fridge, no balls",
    grepl("only", remark) ~ "3 leaves at scanning; mostly brown leaves; 3 leaves at thickness",
    TRUE ~ remark  # keeps all the other remarks the way they were
  ))
  

unique(data$remark)
#ok? with 22 different comments
```

```{r}
#| label: adjusting bulk_nr values per trait

# While the bulk number from the envelope represents the initial sample size, sometimes leaves are lost or gained during the trait sampling process. Need to check comments and the particple count from the leaf area scans to adjust the bulk number leaves for each trait. This needs to be done before calculating per leaf trait values, which can be used for metrics like SLA and LDMC.

# Relies on cleaned remarks column from step above

# Order of trait measurements is: fvfm_initial, wet_mass, leaf_area, leaf_thickness, dry_mass

```

```{r}
#| label: adjusting weird values in the data

## MODIFICATION in the "check leaf thickness outliers (per measurement 1-3 replicates)" part
# for BUI 8 20 leaf_thickness_3_mm is 0.588 instead of 0.249
data <- data %>%
  mutate(leaf_thickness_3_mm = case_when(
    grepl("0.588", leaf_thickness_3_mm) ~ 0.249,
    TRUE ~ leaf_thickness_3_mm
  ))

## month MODIFICATION
data <- data %>%
  mutate(month = case_when(
    grepl("January", month) ~ "March",
    TRUE ~ month
  ))

## temp_exp --> témoin
#data <- data %>%
  #mutate(temp_exp = case_when(
    #is.na(temp_exp) ~ "témoin",  # replace NA by "témoin"
    #TRUE ~ as.character(temp_exp)
  #))

## missing value for NB7 leaf 16 (not correct in the raw data frame)
data <- data %>%
  mutate(wet_mass_g = if_else(is.na(wet_mass_g), 0.01063, wet_mass_g))
```

# Calculate per leaf trait values

```{r}
#| label: calculate bulk nr for each trait

# Before checking for outliers, need to convert traits to 'per leaf' values, else outliers might simply reflect a shift in the leaf numbers for 'absolute' values.

# Note, this is only for wet mass, leaf area, dry mass.
# For fluorescence this is per sample in the clip
# For thickness, each measurement (1-3) needs to be checked first, then averaged in cae one of the replicate samples is an outlier and will skew the average thickness


# Default column is the intiial bulk_nr, initial values for following trait derived from prior trait + edits via comments

data$bulk_nr_wet_mass <- data$bulk_nr_leaves


# Modify based on the wet mass comments
data <- data %>%
  mutate(bulk_nr_wet_mass = case_when(
    grepl("3 leaves at wet mass", remark) ~ 3,
    .default = bulk_nr_wet_mass    # Keep original bulk nr value if no comment is applied to row
  ))

# Create leaf area, rename the particle counts from scanner. More accurate then comments for values less than 4. However, sometimes leaves break into multiple parts, so the particle count may be higher than the leaf count artificially.
data <- data %>% 
  rename(bulk_nr_leaf_area = leaf_area_scanned_bulk_nr)

# Modify based on the wet mass comments
data <- data %>%
  mutate(bulk_nr_leaf_area = case_when(
    # Checked against images, indeed 5 leaves (not broken)
    grepl("5 leaves at scanning", remark) ~ 5,
    grepl("3 leaves at scanning", remark) ~ 3,
    .default = bulk_nr_leaf_area    # Keep original bulk nr value if no comment is applied to row
  ))

# Check count of leaf numbers by the remark column to help identify issues
# We have 5, 6, 7 and 8's
table(data$remark, data$bulk_nr_leaf_area)

# Find rows where leaf number for area is higher than leaf number for wet mass
# Need to go and check 1) leaf scans, 2) envelopes to see if extra particles are in envelope, 3) remarks column, 4) the excel tab on leaf area checks
bulk_nr_issues <- data %>%
  filter(bulk_nr_leaf_area > bulk_nr_wet_mass) %>% 
  select(envelope_ID, remark, bulk_nr_leaves, bulk_nr_wet_mass, bulk_nr_leaf_area)


# Address each outcome by envelope_ID
# AEI1422 actually has 5 leaves- see comment edit above
# ADM0437 actually has 5 leaves - see comment edit above
# All other envelopes have correct number based on the wet mass column in the images, so correct back to the wet mass values


# Modify based on the comments, checking images etc. 
data <- data %>%
  mutate(bulk_nr_leaf_area = case_when(
    # Envelope ID's are X, then do Y
    grepl("AEI1422", envelope_ID) ~ 5,
    grepl("ADM0437", envelope_ID) ~ 5,    
    grepl("5 leaves at scanning", remark) ~ 5,
    grepl("3 leaves at scanning", remark) ~ 3,
    .default = bulk_nr_wet_mass    # Keep original bulk nr value if no comment is applied to row
  ))




# Note, for thickness the value is note correct by bulk leaf number, however, if there are fewer than three leaves, there may only be one or two leaf thickness measurements to average across. 
data$bulk_nr_thickness <- data$bulk_nr_leaf_area

# Check how many envelopes have fewer than three thickness measurements
bulk_nr_issues_thickness <-  data %>%
  filter(rowSums(across(starts_with("leaf_thickness_"), ~ . > 0)) < 3)

# No issues!

# Modify based on the thickness comments
data <- data %>%
  mutate(bulk_nr_thickness = case_when(
    grepl("3 leaves at thickness", remark) ~ 3,
    grepl("5 leaves at thickness", remark) ~ 5,
    .default = bulk_nr_thickness    # Keep original bulk nr value if no comment is applied to row
  ))


# Create dry mass bulk nr based on thickness
data$bulk_nr_dry_mass <- data$bulk_nr_thickness

# Modify based on the dry mass comments
data <- data %>%
  mutate(bulk_nr_dry_mass = case_when(
    grepl("3 leaves at dry mass", remark) ~ 3,
    grepl("5 leaves at dry mass", remark) ~ 5,
    .default = bulk_nr_dry_mass    # Keep original bulk nr value if no comment is applied to row
  ))
#ok?
```

```{r}
#| label: calculate per leaf values for each trait

data <- data %>% 
  mutate(
    wet_mass = wet_mass_g / bulk_nr_wet_mass,
    leaf_area = leaf_area_sum / bulk_nr_leaf_area,
    dry_mass = dry_mass_g / bulk_nr_dry_mass
  ) %>% 
  # Round the decimal places
  mutate(
    wet_mass = round(wet_mass, digits = 5),
    leaf_area = round(leaf_area, digits = 3),
    dry_mass = round(dry_mass, digits =  5)
  )
#ok!
```

# Check trait outliers

```{r}
#| label: check plant height (vegetative) outliers

# making a scatterplot for vegetative plant height per plant
(data %>% 
         filter(proj_2025 == "Traits") %>% 
       ggplot(aes(x = factor(plant_nr), y = height_vegetative, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Plant Height - Vegetative (cm)",
    title = "Mean Vegetative Plant Height (cm) by plant, age class and month"
  ))


# making a scatterplot for flowering plant height per plant
(data %>% 
         filter(proj_2025 == "Traits") %>% 
       ggplot(aes(x = factor(plant_nr), y = height_flower, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Plant Height - Flowering (cm)",
    title = "Mean Flowering Plant Height (cm) by plant, age class and month"
  ))


# Flowering vs vegetative plant height
# Flowering height should probably be taller than vegetative height
# So above the 1:1 line

ggplot(data %>%  filter(proj_2025 == "Traits"),
       aes(x = height_vegetative, y = height_flower)) +
  
  # scatter points
  geom_point(aes(colour = factor(plant_nr), shape = factor(age_class)),
             size = 2, alpha = 0.7) +
  
  # 1:1 reference line
  geom_abline(slope = 1, intercept = 0,
              linetype = "dashed", colour = "grey50") +
  
  # fitted regression line
  geom_smooth(method = "lm", se = TRUE, colour = "blue") +
  
  # optional: label
  labs(
    x = "Vegetative Height (cm)",
    y = "Flowering Height (cm)",
    title = "Flowering vs Vegetative Plant Height",
    subtitle = "Dashed line = 1:1 reference, blue line = fitted linear trend",
    colour = "plant_nr"
  ) +
  
  theme_bw()

# vegetation height --> ok
# flower height --> NB 7 without flowering height but ok
# flowering height always bigger than vegetative height --> height
```

```{r}
#| label: check wet mass outliers (per leaf)

# making a scatterplot for wet mass mean for trait leaves, plant_nr on x-axis and weight in g on y-axis
(data %>% 
         filter(proj_2025 == "Traits") %>% 
       ggplot(aes(x = factor(plant_nr), y = wet_mass, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Wet mass (g)",
    title = "Mean wet mass per leaf by plant, age class and month"
  ))

# wet mass ok exept one for PIO 5 ~ 0.007
```

```{r}
#| label: check leaf area outliers (per leaf)

# making scatterpolt for leaf area mean for trait leaves, plant_nr on x-axis and mean leaf area on y-axis. by plant nr, age class, month 
ggplot(data %>%  filter(proj_2025 == "Traits"),
       aes(x = factor(plant_nr), y = leaf_area, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Leaf area (mm2)",
    title = "Leaf area by plant, age class and month"
  )

# Check source file issues
ggplot(data %>%  filter(proj_2025 == "Traits"),
       aes(x = factor(plant_nr), y = leaf_area, colour = factor(source_file))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Leaf area (mm2)",
    title = "Leaf area by plant, age class and month"
  )

# Check source file issues
ggplot(data %>%  filter(proj_2025 == "Traits"),
       aes(x = factor(plant_nr), y = leaf_area, colour = factor(source_file))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ source_file) +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(
    x = "Plant number",
    y = "Leaf area (mm2)",
    title = "Leaf area by plant, age class and month"
  )

# bigger leaves for NB and smaller for the others
# for PIO : leaf area small edited image bigger than non edited one --> ?
# small edited images seem often to be plant 5 to 8 and large one plante 1 to 4
```

```{r}
#| label: check leaf thickness outliers (per measurement 1-3 replicates)
# histogram for leaf thickness distribution for trait leaves, not mean, rather seperate reps

data_long_thickness <- data %>% 
  filter(proj_2025 == "Traits") %>% 
  pivot_longer( # to get the seperate columns reshaped
    cols = c(leaf_thickness_1_mm, leaf_thickness_2_mm, leaf_thickness_3_mm),
    names_to = "replicate",
    values_to = "leaf_thickness_mm"
  )

ggplot(data_long_thickness, #plotting drom long format
       aes(x = factor(plant_nr), y = leaf_thickness_mm, colour = factor(leaf_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Leaf thickness (mm)",
    title = "Leaf thickness replicates by plant, age class and month"
  )



ggplot(data_long_thickness, #plotting drom long format
       aes(x = factor(plant_nr),
           y = leaf_thickness_mm,
           colour = factor(leaf_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(leaf_nr ~ age_class) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Leaf thickness (mm)",
    title = "Leaf thickness replicates by plant, age class and month"
  )

# weird values to check : BUI 1 19 0.25 ; BUI 8 20 0.6
# BUI 1 19 0.25 --> seems ok ; BUI 8 20 0.6 ; PIO 2 20 0.6
# for BUI 8 20 leaf_thickness_3_mm is 0.588 instead of 0.249 --> modification code is "data cleaning entire frame"
# other values are fine
```

```{r}
#| label: check dry mass outliers (per leaf)

# making a scatterplot for dry mass mean for trait leaves, plant_nr on x-axis and weight in g on y-axis
ggplot(data |> filter(proj_2025 == "Traits"),
       aes(x = factor(plant_nr), y = dry_mass, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Dry mass (g)",
    title = "Mean dry mass per leaf by plant, age class and month"
  )

# values seem ok ; may be PIO 5 values are a little bit higher than the others PIO
# 2 low values for dry mass plant 6 for BUI and MAT
```

```{r}
#| label: wet mass vs dry mass


ggplot(data %>%  filter(proj_2025 == "Traits"),
       aes(x = wet_mass_g, y = dry_mass_g)) +
  
  # scatter points
  geom_point(aes(colour = factor(plant_nr)),
             size = 2, alpha = 0.7) +
  
  # 1:1 reference line
  geom_abline(slope = 1, intercept = 0,
              linetype = "dashed", colour = "grey50") +
  
  # fitted regression line
  geom_smooth(method = "lm", se = TRUE, colour = "blue") +
  
  # optional: label
  labs(
    x = "Wet mass per leaf (g)",
    y = "Dry mass per leaf (g)",
    title = "Dry mass vs wet mass per leaf",
    subtitle = "Dashed line = 1:1 reference, blue line = fitted linear trend",
    colour = "plant_nr"
  ) +
  
  theme_bw()

# according to the graph, dry mass always smaller than wet mass --> ok
# most of the plant have similar dry and wet mass
# relationship between dry and wet mass seem to be linear
# 2 low values for dry mass plant 6 for BUI and MAT (according to the graph just above) --> explain by the fact that the dry mass is already lower than other and we divide it by five since there is five which make it even lower --> high chance the leaves aren't all from this individual --> we may remove this individual later on

ggplot(data %>%  filter(proj_2025 == "Traits"),
       aes(x = wet_mass_g, y = dry_mass_g)) +
  
  # scatter points
  geom_point(aes(colour = factor(plant_nr)),
             size = 2, alpha = 0.7) +
  
  # 1:1 reference line
  geom_abline(slope = 1, intercept = 0,
              linetype = "dashed", colour = "grey50") +
  
  # fitted regression line
  geom_smooth(method = "lm", se = TRUE, colour = "blue") +
  
  facet_wrap(~ age_class) + # wet mass vs dry mass graphs facet by the age classes.
  
  # optional: label
  labs(
    x = "Wet mass per leaf (g)",
    y = "Dry mass per leaf (g)",
    title = "Dry mass vs wet mass per leaf",
    subtitle = "Dashed line = 1:1 reference, blue line = fitted linear trend",
    colour = "plant_nr"
  ) +
  
  theme_bw()

# for PIO 5 values are isolated 
# accordig to the dry mass graph it as a higher dry mass than others and a higher wet mass too 

```

# Calculate SLA and LDMC

#\| label: calculate SLA and LDMC

```{r}
#| label: calculate SLA and LDMC

# Specific Leaf Area (SLA)

####______________INTERPRETATION_____________

## SLA = Leaf Area (mm²) / Leaf dry mass (g)
## High SLA (> 300 000 mm²/g) means fast-growing plants ("Acquisitive strategy"). These plants have thin, flexible leaves that capture light efficiently.
## Low SLA (< 100 000 mm²/g) means slow-growing plants ("Conservative strategy"). These plants have thick, leathery leaves designed to last a long time and resist stress. --> Calluna vulgaris

##___________________________________________

data <- data %>%  
  mutate(
    SLA = ifelse(
      !is.na(leaf_area) & !is.na(dry_mass), # excluding rows with NAs
      leaf_area / dry_mass, # Leaf level metrics
      NA_real_
    )
  )


# Leaf Dry Matter Content (LDMC)

####______________INTERPRETATION_____________

## LDMC = Leaf Dry Mass (g)/ Leaf Fresh Mass (g)
## varies between 0 and 1
## High LDMC (0.5 - 0.7) : Leaves are dense, high in lignin/cellulose, and low in water. They are very resistant to physical hazards and drought.
## Low LDMC (0;05 - 0.5) : Leaves are "succulent" or watery.

##___________________________________________

data <- data %>% 
  mutate(
    LDMC = ifelse( # making new ldmc column
      !is.na(dry_mass) & !is.na(wet_mass), # excluding rows with NAs
      dry_mass / wet_mass, # Leaf level metrics
      NA_real_
    )
  )
```

```{r}
#| label: check SLA outliers (per leaf)

# making a scatterplot for dry mass mean for trait leaves, plant_nr on x-axis and weight in g on y-axis
ggplot(data %>%  filter(proj_2025 == "Traits"),
       aes(x = factor(plant_nr), y = SLA, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "SLA",
    title = "Mean SLA per leaf by plant, age class and month"
  )

# higher SLA for NB than MAT --> ok 
# high value for BUI 6 probably linked to the low value of dry mass
# no weird value for MAT 6 even if low value for dry mass
```

```{r}
#| label: check LDMC outliers (per leaf)

# making a scatterplot for dry mass mean for trait leaves, plant_nr on x-axis and weight in g on y-axis
ggplot(data %>%  filter(proj_2025 == "Traits"),
       aes(x = factor(plant_nr), y = LDMC, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "Leaf Dry Matter Content (LDMC)",
    title = "Mean LDMC per leaf by plant, age class and month"
  )

# LDMC rise with the age of the plant --> ok because leaves from mature plant are more structured with lignine for example
# weird value for BUI 6 and MAT 6 --> may be linked to the 2 low values in the graph of dry mass
```

# Check fluorescence outliers

```{r}
#| label: check fluorescence outliers

# making a scatterplot for initial fluorescence
(data %>% 
         filter(proj_2025 == "Traits") %>% 
       ggplot(aes(x = factor(plant_nr), y = fv_fm_initial, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "fv_fm_initial",
    title = "Initial fluorescence by plant, age class and month"
  ))

(data %>% 
         filter(proj_2025 == "TT Hot") %>% 
       ggplot(aes(x = factor(plant_nr), y = fv_fm_final, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "fv_fm_final",
    title = "Final fluorescence TT Hot by plant, age class and month"
  ))

(data %>% 
         filter(proj_2025 == "TT Cold") %>% 
       ggplot(aes(x = factor(plant_nr), y = fv_fm_final, colour = factor(plant_nr))) +
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Plant number",
    y = "fv_fm_final",
    title = "Final fluorescence TT Cold by plant, age class and month"
  ))
# one value is registered as a January one --> modification is in data cleaning entire frame

#### Initial fluorescence
# MAT 3 have a high fv/fm ; same for BUI 5 
# low points for NB 5, 7 and 8 --> maybe due to the season

#### final fluorescence TT Hot 
# High value for BUI 4 (we don't have that in the initial fluo graph)
```

```{r}
#| label: check fluorescence outliers TT Hot


data %>% 
  filter(proj_2025 == "TT Hot") %>% 
  
  ggplot(aes(x = as.numeric(as.character(temp_exp)), 
             y = fv_fm_final,
             group = plant_nr,      
             color = plant_nr)) +
  
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  geom_line() +

  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Temperature",
    y = "fv_fm_final",
    title = "Fv/Fm response to hot temperature across plants, age classes and months"
  )

```

```{r}
#| label: check fluorescence outliers TT Cold

data %>% 
  filter(proj_2025 == "TT Cold") %>% 
  mutate(temp_exp = factor(temp_exp, levels = c("5", "0", "-5", "-10","-15", "-20"))) %>%
  ggplot(aes(x = temp_exp, 
             y = fv_fm_final,
             group = plant_nr,      
             color = plant_nr)) +
  
  geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
  geom_line() +

  facet_grid(age_class ~ month) +
  theme_bw() +
  labs(
    x = "Temperature",
    y = "fv_fm_final",
    title = "Fv/Fm response to cold temperature across plants, age classes and months"
  )
```

# Hot T50 curves

```{r}
#| label: Create data frame

# Create table with four columns
therm_htol_march<- data %>% 
  #filter(age_class %in% c("Building", "Mature")) %>% #no results for these two # didn't try yet
  filter(proj_2025 == "TT Hot")%>% 
  select(site_name, species, age_class, proj_2025, plant_nr, temp_exp, temp_exp_time, fv_fm_final)

#working
```

```{r}
#| label:  concatenated columns, T50 curves and plots (age_class)

# Create table with concatenated columns for naming
united_columns_htol_march <- unite(
  therm_htol_march,
  col = "new_id",
  site_name, species, age_class, proj_2025,
  sep = "_",
  remove = TRUE
) %>% 
  na.omit()

### T50 CURVES

install.packages("remotes")
remotes::install_github("richardjtelford/thermalTolerance")
library(thermalTolerance)


TTHot_march <- psiiht(temperature = as.numeric(as.character(united_columns_htol_march$temp_exp)), 
               warming = TRUE,
               fvfm = as.numeric(as.character(united_columns_htol_march$fv_fm_final)),
               control_temp = 20,
               id = united_columns_htol_march$new_id,
               boots = 500)#boots can be higher when the script is working

TTHot_march_sum <- summary(TTHot_march) # see summary output for T50 values (note, just means)
# no results for BUI and MAT --> maybe du to the weird curves we obtained earlyer

autoplot(TTHot_march) # plots logistic curves and dashed lines for Tcrit, T50, T95

### PLOT

# Create a summary table that provides the median, standard error, and lower (2.5%) and upper (2.5%) quantiles for each ID and each thermal metric (T50, T95 and Tcrit)

summarise_htol <- function(res, id) {
  
  # si c'est null on met des NA pour que ça ne bloque pas
  if (is.null(res)) {
    return(data.frame(
      id = id,
      metric = c("T50", "T95", "Tcrit"),
      estimate = NA,
      se = NA,
      lower = NA,
      upper = NA
    ))
  } 
  
  # sinon on calucule normalement
  data.frame(
    id = id,
    metric = c("T50", "T95", "Tcrit"),
    estimate = c(median(res$T50, na.rm = TRUE),
                 median(res$T95, na.rm = TRUE),
                 median(res$Tcrit, na.rm = TRUE)),
    se = c(sd(res$T50, na.rm = TRUE),
           sd(res$T95, na.rm = TRUE),
           sd(res$Tcrit, na.rm = TRUE)),
    lower = c(quantile(res$T50, 0.025, na.rm = TRUE),
              quantile(res$T95, 0.025, na.rm = TRUE),
              quantile(res$Tcrit, 0.025, na.rm = TRUE)),
    upper = c(quantile(res$T50, 0.975, na.rm = TRUE),
              quantile(res$T95, 0.975, na.rm = TRUE),
              quantile(res$Tcrit, 0.975, na.rm = TRUE))
  )
}

# Run the summarize function for each ID output
TTHot_march_out <- Map(
  summarise_htol, # function
  TTHot_march$results, # extract the results part of the psiiht output
  names(TTHot_march$results)  # extract the ID from the psiiht output
  )
#semble fonctionner

# Create the dataframe by rowbinding 
TTHot_thermal <- do.call(rbind, TTHot_march_out)
#on obtient un tableau

# String split back to columns the ID, nouveau tableau
TTHot_wide <- TTHot_thermal %>%
  separate_wider_delim(
    cols = id, # the column to split
    delim = "_", # how is the column seperated
    # what should the new columns be called - do in order
    names = c("site_name", "species", "age_class", "proj_2025") #,
   # too_many = "merge", # Merges any extra parts into the last column
   # too_few = "align_start" # Fills missing values with NA
  ) %>% 
  # Check the data type of the new output columns and convert if necessary
   mutate(
    age_class = factor(age_class),
    proj_2025 = factor(proj_2025),
    site_name = factor(site_name),
    species = factor(species)
  ) %>% 
  # Relevel factors in natural order
  mutate(
    age_class = factor(age_class, levels = c("Newly Burnt","Pioneer","Building", "Mature")))

# Create a preliminary plot focusing on T50 metric
TTHot_wide %>% 
  filter(metric == "T50") %>% 
ggplot(aes(x = age_class,
           y = estimate,
           color = proj_2025)) +
  geom_point(size = 3,
              position = position_dodge(width = 0.3)) +
  geom_errorbar(aes(ymin = estimate - se, ymax = estimate + se),
                width = 0.2,
                position = position_dodge(width = 0.3)) +
  facet_grid(site_name ~ species) +
  labs(
    x = "Age Class",
    y = "T50 (°C)",
    color = "treatment",
    title = "T50 by Age Class for hot treatment",
    subtitle = "Points show mean bootstrap estimate; bars show ±1 SE"
  ) +
  theme_bw()
```

```{r}
#| label: concatenated columns, T50 curves and plots (per plant)


# Create concatenated columns for naming
united_columns_htol_march_plant <- unite(
  therm_htol_march,
  col = "new_id",
  site_name, species, age_class, proj_2025, plant_nr,
  sep = "_",
  remove = TRUE
) %>% 
  na.omit()

### T50 CURVES

#install.packages("remotes")
#remotes::install_github("richardjtelford/thermalTolerance")
#library(thermalTolerance)

TTHot_march_plant <- psiiht(temperature = as.numeric(as.character(united_columns_htol_march_plant$temp_exp)), 
               warming = TRUE,
               fvfm = as.numeric(as.character(united_columns_htol_march_plant$fv_fm_final)),
               control_temp = 20,
               id = united_columns_htol_march_plant$new_id,
               boots = 200)#boots can be higher when the script is working

TTHot_march_plant_sum <- summary(TTHot_march_plant) # see summary output for T50 values (note, just means)
# no results for BUI and MAT --> maybe du to the weird curves we obtained earlyer

autoplot(TTHot_march_plant) # plots logistic curves and dashed lines for Tcrit, T50, T95

#working, maybe separate the graph
## PROBLEME : je crois que ça run pour tout à chaque fois et pas seulement pour la plante concernéé (comparer htol_list et htol_list_plant)

### PLOTS

summarise_htol_plant <- function(res, id) {
  
  # si c'est null on met des NA pour que ça ne bloque pas
  if (is.null(res)) {
    return(data.frame(
      id = id,
      metric = c("T50", "T95", "Tcrit"),
      estimate = NA,
      se = NA,
      lower = NA,
      upper = NA
    ))
  } 
  
  # sinon on calucule normalement
  data.frame(
    id = id,
    metric = c("T50", "T95", "Tcrit"),
    estimate = c(median(res$T50, na.rm = TRUE),
                 median(res$T95, na.rm = TRUE),
                 median(res$Tcrit, na.rm = TRUE)),
    se = c(sd(res$T50, na.rm = TRUE),
           sd(res$T95, na.rm = TRUE),
           sd(res$Tcrit, na.rm = TRUE)),
    lower = c(quantile(res$T50, 0.025, na.rm = TRUE),
              quantile(res$T95, 0.025, na.rm = TRUE),
              quantile(res$Tcrit, 0.025, na.rm = TRUE)),
    upper = c(quantile(res$T50, 0.975, na.rm = TRUE),
              quantile(res$T95, 0.975, na.rm = TRUE),
              quantile(res$Tcrit, 0.975, na.rm = TRUE))
  )
}

# Run the summarize function for each ID output
TTHot_march_plant_out <- Map(
  summarise_htol_plant, # function
  TTHot_march_plant$results, # extract the results part of the psiiht output
  names(TTHot_march_plant$results)  # extract the ID from the psiiht output
  )
#semble fonctionner

# Create the dataframe by rowbinding 
TTHot_thermal_plant <- do.call(rbind, TTHot_march_plant_out)

# String split back to columns the ID
TTHot_wide_plant <- TTHot_thermal_plant %>%
  separate_wider_delim(
    cols = id, # the column to split
    delim = "_", # how is the column seperated
    # what should the new columns be called - do in order
    names = c("site_name", "species", "age_class", "proj_2025", "plant_nr") #,
   # too_many = "merge", # Merges any extra parts into the last column
   # too_few = "align_start" # Fills missing values with NA
  ) %>% 
  # Check the data type of the new output columns and convert if necessary
   mutate(
    age_class = factor(age_class),
    proj_2025 = factor(proj_2025),
    site_name = factor(site_name),
    species = factor(species),
    plant_nr = factor(plant_nr)
  ) %>% 
  # Relevel factors in natural order
  mutate(
    age_class = factor(age_class, levels = c("Newly Burnt","Pioneer", "Building", "Mature")))

# Create a preliminary plot focusing on T50 metric
TTHot_wide_plant %>% 
  filter(metric == "T50") %>% 
ggplot(aes(x = age_class,
           y = estimate,
           color = plant_nr)) +
  geom_point(size = 2,
              position = position_dodge(width = 0.6)) +
  geom_errorbar(aes(ymin = estimate - se, ymax = estimate + se),
                width = 0.2,
                position = position_dodge(width = 0.6)) +
  facet_grid(site_name~species) +
  labs(
    x = "Age Class",
    y = "T50 (°C)",
    color = "plant_nr",
    title = "T50 for each plant for TT Hot by age class",
    subtitle = "Points show mean bootstrap estimate; bars show ±1 SE"
  ) +
  theme_bw()
#working for 50 but not 500 ?
#marche avec 200 mais les barres au niveau de la plante 5 et 4 s'agrandissent 
```

```{r}
#| label: effect of age_class on T50 (ANOVA)

# Does the age_class has an effect on the T50 ?
# H0 : age_class doesn't have an effect on T50 
# H1 : age_class has an effect on T50

# Create data frame 

T50_TTHot <- TTHot_wide_plant %>%
  filter(metric == "T50") %>%
  select(site_name, species, age_class, plant_nr, estimate, se, lower, upper)

# we can do a simple ANOVA (analyse of variance) because we only have one T50 per plant for each class

modele <- lm(estimate ~ age_class, data = T50_TTHot)
summary(modele)
anova(modele) # age_class has an effect on T50


## Validation of hypotheses (ANOVA)

# Independance of observations
# Observations are independante

# Homoscedasticity
plot(modele, which = 1) # Not sure

# Normality of residuals (Shapiro-Wilk)
shapiro.test(residuals(modele)) # if p-value > 0.05 --> normality ok
plot(model, which = 2)

# Graph
boxplot(estimate ~ age_class, data = T50_TTHot, 
        main = "age_class effect on T50",
        ylab = "Estimate (T50)", 
        col = c("lightblue", "orange", "lightgreen"))

# no significatif difference between nb and pio but with mat yes (/!\ we only have one T50...)

ggplot(T50_TTHot, aes(x = age_class, y = estimate, fill = age_class)) +
  # Le violon (densité)
  geom_violin(trim = FALSE, alpha = 0.5) + 
  # Le boxplot à l'intérieur (plus fin)
  geom_boxplot(width = 0.1, color = "black", outlier.shape = NA) +
  # Optionnel : ajouter les points réels pour montrer l'échantillonnage
  geom_jitter(width = 0.1, alpha = 0.5) +
  # Cosmétique
  theme_minimal() +
  labs(title = "age_class effect on T50",
       x = "age_class",
       y = "Estimate T50") +
  theme(legend.position = "none") # On enlève la légende si l'axe X suffit
```

# Plant functional traits and T50

```{r}
#| label: influence of given traits on T50 (informal)
# given plant functional traits : leaf area, dry mass, SLA, LDMC, height

# Create data frame for the traits
traits_data_frame <- data %>%
  filter(proj_2025 == "Traits")%>% 
  select(site_name, species, age_class, plant_nr, height_flower, height_vegetative, leaf_area, dry_mass, SLA, LDMC)
# /!\ ligne 91 : NB7 has no LDMC --> all good

traits_united_columns <- unite(
  traits_data_frame,
  col = "new_id",
  site_name, species, age_class, plant_nr,
  sep = "_",
  remove = TRUE
) %>% 
  na.omit()

# Create data frame with T50 for hot tolerance
T50_data_frame <- TTHot_wide_plant %>%
  filter(metric == "T50") %>%
  select(site_name, species, age_class, plant_nr, estimate, se, lower, upper)

T50_united_columns <- unite(
  T50_data_frame,
  col = "new_id",
  site_name, species, age_class, plant_nr,
  sep = "_",
  remove = TRUE
) %>% 
  na.omit()

# Create a joint data frame
traits_T50_joint <- left_join(traits_united_columns, T50_united_columns, by = "new_id")

# String split back to columns the ID
traits_T50_joint_wide <- traits_T50_joint %>%
  separate_wider_delim(
    cols = new_id, # the column to split
    delim = "_", # how is the column seperated
    # what should the new columns be called - do in order
    names = c("site_name", "species", "age_class", "plant_nr") #,
   # too_many = "merge", # Merges any extra parts into the last column
   # too_few = "align_start" # Fills missing values with NA
  ) %>% 
  # Check the data type of the new output columns and convert if necessary
   mutate(
    age_class = factor(age_class),
    site_name = factor(site_name),
    species = factor(species),
    plant_nr = factor(plant_nr)
  ) %>% 
  # Relevel factors in natural order
  mutate(
    age_class = factor(age_class, levels = c("Newly Burnt","Pioneer", "Building", "Mature")))

data_scaled <- traits_T50_joint_wide %>%
  mutate(
    height_flower_sc = as.numeric(scale(height_flower)),
    leaf_area_sc     = as.numeric(scale(leaf_area)),
    dry_mass_sc      = as.numeric(scale(dry_mass)),
    SLA_sc           = as.numeric(scale(SLA)),
    LDMC_sc          = as.numeric(scale(LDMC)),
    height_vegetative_sc = as.numeric(scale(height_vegetative)),
  )
```

```{r}
#| label: T50 and SLA

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(SLA)), y = as.numeric(as.character(estimate)), colour = factor(age_class))) + 
    geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
    theme_bw() +
    labs(
      x = "SLA",
      y = "T50 estimate",
      title = "T50 by SLA per age class"
    ))

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(SLA)), y = as.numeric(as.character(estimate)), colour = factor(plant_nr))) + 
    geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
    facet_grid(.~ age_class) +
    theme_bw() +
    labs(
      x = "SLA",
      y = "T50 estimate",
      title = "T50 by SLA per age class"
    ))
```

```{r}
#| label: T50 and LDMC

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(LDMC)), y = as.numeric(as.character(estimate)), colour = factor(age_class))) + 
    geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
    theme_bw() +
    labs(
      x = "LDMC",
      y = "T50 estimate",
      title = "T50 by LDMC per age class"
    ))

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(LDMC)), y = as.numeric(as.character(estimate)), colour = factor(plant_nr))) + 
    geom_point(size = 2, alpha = 0.8,
             position = position_jitter(width = 0.15)) +
    facet_grid(.~ age_class) +
    theme_bw() +
    labs(
      x = "LDMC",
      y = "T50 estimate",
      title = "T50 by LDMC per age class"
    ))
```

```{r}
#| label: T50 and heights

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(height_flower)), y = as.numeric(as.character(estimate)), colour = factor(age_class))) + 
    geom_point() +
    theme_bw() +
    labs(
      x = "flower height",
      y = "T50 estimate",
      title = "T50 by flower height per age class"
    ))

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(height_flower)), y = as.numeric(as.character(estimate)), colour = factor(plant_nr))) + 
    geom_point() +
    facet_grid(.~ age_class) +
    theme_bw() +
    labs(
      x = "flower height",
      y = "T50 estimate",
      title = "T50 by flower height per age class"
    ))

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(height_vegetative)), y = as.numeric(as.character(estimate)), colour = factor(age_class))) + 
    geom_point() +
    theme_bw() +
    labs(
      x = "vegetative height",
      y = "T50 estimate",
      title = "T50 by vegetative height per age class"
    ))

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(height_vegetative)), y = as.numeric(as.character(estimate)), colour = factor(plant_nr))) + 
    geom_point() +
    facet_grid(.~ age_class) +
    theme_bw() +
    labs(
      x = "vegetative height",
      y = "T50 estimate",
      title = "T50 by vegetative height per age class"
    ))

# /!\ je crois que les points se superposent
```

```{r}
#| label: T50 and leaf area

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(leaf_area)), y = as.numeric(as.character(estimate)), colour = factor(age_class))) + 
    geom_point() +
    theme_bw() +
    labs(
      x = "leaf area",
      y = "T50 estimate",
      title = "T50 by leaf area per age class"
    ))

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(leaf_area)), y = as.numeric(as.character(estimate)), colour = factor(plant_nr))) + 
    geom_point() +
    facet_grid(.~ age_class) +
    theme_bw() +
    labs(
      x = "leaf area",
      y = "T50 estimate",
      title = "T50 by leaf area per age class"
    ))

```

```{r}
#| label: T50 and dry mass

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(dry_mass)), y = as.numeric(as.character(estimate)), colour = factor(age_class))) + 
    geom_point() +
    theme_bw() +
    labs(
      x = "dry mass",
      y = "T50 estimate",
      title = "T50 by dry mass per age class"
    ))

(traits_T50_joint_wide %>%
    ggplot(aes(x = as.numeric(as.character(dry_mass)), y = as.numeric(as.character(estimate)), colour = factor(plant_nr))) + 
    geom_point() +
    facet_grid(.~ age_class) +
    theme_bw() +
    labs(
      x = "dry mass",
      y = "T50 estimate",
      title = "T50 by dry mass per age class"
    ))

```

```{r}
#| label: régression linéaire multiple (pas adapté ici)
# ## régression linéaire multiple : sert à predire la T50 en fonction de pls variables (SLA, LDMC,...) /!\ on parle de données indep et ici elles ne le sont pas
# 
# # creation du modèle 
# T50_model = lm(formula = estimate ~ SLA + LDMC + height_flower + height_vegetative + dry_mass + leaf_area, data = traits_T50_joint_wide)
# summary(T50_model)
# 
# ## vérification de la normalité des residus
# T50_model_res = T50_model$residuals
# hist(T50_model_res) # histogramme asymétrique vers la gauche
# qqnorm(T50_model_res)
# qqline(T50_model_res) # Les points suivent la ligne --> normalité ok 
# 
# ## hypothèse de multicolinéarité
# install.packages("ggcorrplot")
# library(ggcorrplot)
# 
# var_data_frame <- traits_T50_joint_wide %>%
#   select(height_flower, height_vegetative, dry_mass, leaf_area, SLA, LDMC)
# 
# # matrice de corrélation bivariée
# corr_matrix = round(cor(var_data_frame), 2)
# # résultat
# ggcorrplot(corr_matrix, hc.order = TRUE, type = "lower",
#           lab = TRUE)
# # dry_mass et leaf_area : 0.81
# # height_flower et height_vegetative : 0.99
# # on enlève la height_flower car on s'intéresse aux feuilles
# # on envlève dry_mass et leaf_area car ils sont lié dans la SLA
# 
# # création d'un nouveau modèle
# T50_model_2 = lm(formula = estimate ~ SLA + LDMC + height_vegetative, data = traits_T50_joint_wide)
# 
# summary(T50_model_2) #seul le LDMC a une influence significative sur la T50
# 
# ## vérification de la normalité des residus
# T50_model_res = T50_model_2$residuals
# hist(T50_model_res) # histogramme asymétrique vers la gauche
# qqnorm(T50_model_res)
# qqline(T50_model_res) # Les points suivent la ligne --> normalité ok 
# 
# ## hypothèse de multicolinéarité
# install.packages("ggcorrplot")
# library(ggcorrplot)
# 
# var_data_frame <- traits_T50_joint_wide %>%
#   select(height_vegetative, SLA, LDMC)
# 
# # matrice de corrélation bivariée
# corr_matrix = round(cor(var_data_frame), 2)
# # résultat
# ggcorrplot(corr_matrix, hc.order = TRUE, type = "lower",
#           lab = TRUE)
# # normailté et corrélation ok après ces retraits 
# 
# ## --> quel modèle est le meilleur ?
# # vérification avec une ANOVA
# # H0 : les variables supprimées ne sont pas significatives
# # H1 : ces variables sont significatives
# 
# # ANOVA test
# anova(T50_model, T50_model_2)
# # Même si model 1 est apparement mieux il y a multicolinéraité ce qui le fait bugger donc on prend le modèle 2
```

```{r}
#| label: Lineare Mixed Model with Nested effects

## /!\ hypothèses à vérifier pour une LMM

# 1. normalité des résidus
# 2. homoscédasticité
# 3. indépendance des résidus
# 4. normalité des effets aléatoires
# 5. structure correcte des effets aléatoires
# 6. absence de colinéarité (effets fixes)
# 7. linéarité (effets fixes)
# bonus. diagnostique de R

install.packages("lme4")
library(lme4)

model_march <- lmer(estimate ~ age_class * (SLA_sc + LDMC_sc) + # Fixed effects: we want to know if age_class and traits have an effect on T50. * Traits vary throughout age_class, so they are dependent.
        (1 | age_class:plant_nr), # Random effect: we have a random effect (plant_nr) nested within a fixed effect (age_class).
        data = data_scaled)
isSingular(model_march) # FALSE --> justify the random effect of plant_nr

summary(model_march)

#not working...






# 1.
qqnorm(residuals(model_march_2)) 
qqline(residuals(model_march_2)) # normalité des res ok

# 2.
plot(model_march_1) # les points sont aléatoires autour de la droite 0 --> homoscédasticité respectée + linéarité respectée (pas de forme de U)

# 3.
residus <- residuals(model_march_2)

plot(residus, 
     type = "b",
     pch = 19, 
     col = "steelblue",
     main = "Indépendance des résidus",
     xlab = "Index de l'observation",
     ylab = "Résidus")
abline(h = 0, lty = 2, col = "red") # Ajout d'une ligne à zéro

acf(resid(model_march_2),
    main = "ACF des résidus")
# peut-être qu'il y a auto-corrélation je ne sais pas trop

# 4.
effets_aleatoires <- ranef(model_march_2)$plant_nr
qqnorm(effets_aleatoires[, "(Intercept)"], 
       main = "Normalité des effets aléatoires (Plantes)",
       pch = 19, col = "darkgreen")
qqline(effets_aleatoires[, "(Intercept)"], col = "red")
# courbe un peu en forme de S --> normalité ~~

# 5. 
# On crée le modèle simple (sans effet aléatoire) avec lm()
model_simple_2 <- lm(estimate ~ SLA + LDMC + height_flower + height_vegetative + age_class, 
                   data = traits_T50_joint_wide)
## AIC du LMM plus petit que LMS (différence de plus de 2 --> significatif)

# On compare les deux modèles
AIC(model_simple_2, model_march_2)
# on vérifie la "singularité" (si le modèle a planté car trop complexe)
isSingular(model_march_1) # FALSE --> justify the random effect of plant_nr

# 6. 
install.packages("car")
library(car)

# Calcul du VIF (Variance Inflation Factor)
vif(model_march_2)
## il y a un pb --> à voir 

# 7.
install.packages("performance")
install.packages("see") 
library(performance)

check_model(model_march_2, check = "linearity")
# ok ?

# bonus. 

library(DHARMa)

sim_res_calluna <- simulateResiduals(fittedModel = model_march_2)
plot(sim_res_calluna)
# ok?
```
