---
title: "DURIN 2026 Thermal Tolerance Vm"
author: "Sonya R Geange and Gaëlle Poulat"
format: html
editor: visual
---

## Import Data

```{r}
#| label: loading libraries
#| message: false 

# installing / loading packages

library(readxl) # Enables excel file import
library(tidyverse) # Contains many helpful packages, i.e. dplyr etc.
library(janitor) # Has tools for data cleaning 
library(lubridate) # Date and time formatting
library(readr) # Data importation functions
library(stringr) # String and character text
```

```{r}
#| label: importing raw data of trait and fluorescence
#| message: false 

# Eventually this will download from the DURIN OSF
# For now, download the excel from google sheets and save in your projects 'raw_data' folder.
# If using projects just need "./filenam.xlsx'
# If not in projects, need full path name

# Read in fluorescence and plant functional trait data (excluding leaf area)
raw_data <- read_excel(
  "C:/Users/poula/Documents/M2_PAMEQ/Stage M2/Analyse statistique/thermotolerance/data/raw_data/Seasonal Calluna Thermal Tolerance and Plant Functional Traits.xlsx", 
  sheet = "cv_mar26", # Choose the sheet from excel
  na = c("", "NA")) # NAs are actually imported as NAs, not as characters 
```
